query GetCompany($id: ID!) {
	getCompany(id: $id) {
		id
		attributes {
			field {
				description
				id
				name
			}
			stringValue
		}

		documentCollections {
			name
			id
		}
		investingEntity {
			name
			id
		}
	}
}
