mutation UpsertInvestmentCriterion(
	$fieldId: ID!
	$input: UpsertInvestmentCriterionInput!
	$investingEntityId: ID!
) {
	upsertInvestmentCriterion(
		fieldId: $fieldId
		input: $input
		investingEntityId: $investingEntityId
	) {
		enabled
		required
		rules
	}
}
