/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import { AWS_REGION, COGNITO_CLIENT_ID, COGNITO_USER_POOL_ID } from '$lib/config';

const awsConfig = {
	aws_project_region: AWS_REGION,
	aws_cognito_region: AWS_REGION,
	aws_user_pools_id: COGNITO_USER_POOL_ID,
	aws_user_pools_web_client_id: COGNITO_CLIENT_ID,
	// oauth: {
	// 	domain: `$USER_POOL_DOMAIN.auth.${AWS_REGION}.amazoncognito.com`
	// },
	aws_cognito_username_attributes: ['EMAIL'],
	aws_cognito_social_providers: [],
	aws_cognito_signup_attributes: [],
	aws_cognito_mfa_configuration: 'OFF',
	aws_cognito_mfa_types: [],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: [
			'REQUIRES_LOWERCASE',
			'REQUIRES_UPPERCASE',
			'REQUIRES_NUMBERS',
			'REQUIRES_SYMBOLS'
		]
	},
	aws_cognito_verification_mechanisms: ['EMAIL']
};

export default awsConfig;
